//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bin2019.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bin2019.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage actions_addcircled {
            get {
                object obj = ResourceManager.GetObject("actions_addcircled", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage actions_addcircled1 {
            get {
                object obj = ResourceManager.GetObject("actions_addcircled1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage actions_remove {
            get {
                object obj = ResourceManager.GetObject("actions_remove", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage actions_sum {
            get {
                object obj = ResourceManager.GetObject("actions_sum", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_appearance {
            get {
                object obj = ResourceManager.GetObject("bo_appearance", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_localization {
            get {
                object obj = ResourceManager.GetObject("bo_localization", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_note {
            get {
                object obj = ResourceManager.GetObject("bo_note", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_note1 {
            get {
                object obj = ResourceManager.GetObject("bo_note1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_note2 {
            get {
                object obj = ResourceManager.GetObject("bo_note2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_position {
            get {
                object obj = ResourceManager.GetObject("bo_position", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_position1 {
            get {
                object obj = ResourceManager.GetObject("bo_position1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_position2 {
            get {
                object obj = ResourceManager.GetObject("bo_position2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage bo_validation {
            get {
                object obj = ResourceManager.GetObject("bo_validation", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage changeview {
            get {
                object obj = ResourceManager.GetObject("changeview", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage changeview1 {
            get {
                object obj = ResourceManager.GetObject("changeview1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage charttype_bubble {
            get {
                object obj = ResourceManager.GetObject("charttype_bubble", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage manual {
            get {
                object obj = ResourceManager.GetObject("manual", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap nodata {
            get {
                object obj = ResourceManager.GetObject("nodata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage open2 {
            get {
                object obj = ResourceManager.GetObject("open2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage open21 {
            get {
                object obj = ResourceManager.GetObject("open21", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap reset_16x16 {
            get {
                object obj = ResourceManager.GetObject("reset_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap reset_32x32 {
            get {
                object obj = ResourceManager.GetObject("reset_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage save_as {
            get {
                object obj = ResourceManager.GetObject("save as", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage save_as1 {
            get {
                object obj = ResourceManager.GetObject("save as1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage scatterchartlabeloptions {
            get {
                object obj = ResourceManager.GetObject("scatterchartlabeloptions", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage scatterchartlabeloptions1 {
            get {
                object obj = ResourceManager.GetObject("scatterchartlabeloptions1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
    }
}
